# Generated by Django 3.2.5 on 2021-07-15 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code_alpha2', models.CharField(default='', max_length=2)),
                ('code_alpha3', models.CharField(default='', max_length=3)),
                ('numeric_code', models.IntegerField(default=0, null=True)),
                ('loc_lat', models.FloatField(default=0, null=True)),
                ('loc_long', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('threshold_buffer', models.FloatField(default=0)),
                ('grade_boundaries', models.JSONField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_year', models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], max_length=300)),
                ('total_marks', models.FloatField(blank=True, default=0)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.country')),
            ],
        ),
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('threshold_buffer', models.FloatField(default=0)),
                ('classes', models.ManyToManyField(to='QLA.Class')),
                ('exam', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('paper_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('paper_code', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_marks', models.FloatField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('grade_boundaries', models.JSONField(blank=True, null=True)),
                ('threshold_buffer', models.FloatField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.exam')),
                ('exam_board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.examboard')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('urn', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('school_logo', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('is_active', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.country')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('topic_questions', models.FileField(blank=True, upload_to='')),
                ('topic_solutions', models.FileField(blank=True, upload_to='')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.level')),
                ('subject', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.school')),
                ('subjects', models.ManyToManyField(to='QLA.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentYearGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.country')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('student_ref_number', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.school')),
                ('year_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.studentyeargrade')),
            ],
            options={
                'ordering': ['year_grade', 'firstname'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='subjects',
            field=models.ManyToManyField(to='QLA.Subject'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1)),
                ('question_label', models.CharField(max_length=10)),
                ('marks', models.FloatField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.paper')),
                ('topics', models.ManyToManyField(to='QLA.Topic')),
            ],
            options={
                'ordering': ['question_label'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.school')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.subject')),
                ('teachers', models.ManyToManyField(to='QLA.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.subject'),
        ),
        migrations.CreateModel(
            name='MockExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_mark', models.FloatField(default=0)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.mockexam')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.question')),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.school')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.student')),
            ],
        ),
        migrations.AddField(
            model_name='mockexam',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.school'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLA.examboard'),
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_rn', to='QLA.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='QLA.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='year_grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='QLA.studentyeargrade'),
        ),
    ]
