# Generated by Django 3.2.5 on 2021-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='urn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
