# Generated by Django 3.2.5 on 2021-07-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0004_auto_20210716_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade_boundaries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
