# Generated by Django 3.2.5 on 2021-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0005_alter_exam_grade_boundaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_year',
            field=models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=300),
        ),
    ]
