# Generated by Django 3.2.5 on 2021-07-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0006_alter_exam_exam_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='grade_boundaries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
