# Generated by Django 3.2.5 on 2021-07-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0008_auto_20210716_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='QLA.Subject'),
        ),
    ]
