# Generated by Django 3.2.5 on 2021-07-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0011_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='QLA.Subject'),
        ),
    ]
