# Generated by Django 3.2.5 on 2021-08-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0012_alter_school_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='PaperFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
