# Generated by Django 3.2.5 on 2021-08-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0013_exam_paperfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='QLA.Teacher'),
        ),
    ]
