# Generated by Django 3.2.5 on 2021-07-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0012_alter_school_subjects'),
        ('bundle', '0004_bundle_annual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='Subjects',
            field=models.ManyToManyField(to='QLA.Subject'),
        ),
    ]
