# Generated by Django 3.2.5 on 2021-07-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'School',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.school'),
        ),
    ]
