# Generated by Django 3.2.5 on 2021-07-18 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9](\\.?[a-z0-9]){5,}@g(oogle)?mail\\.com$', 'only valid email is required')]),
        ),
    ]
