# Generated by Django 3.2.5 on 2021-07-19 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(choices=[('Super_User', 'Super_User'), ('Account_Admin', 'Account_Admin'), ('Head_of_Subject', 'Head_of_Subject'), ('Subject_Teacher', 'Subject_Teacher'), ('Head_Teacher', 'Head_Teacher'), ('Print_Manager', 'Print_Manager')], default='Super_User', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_domain', message='Domain not valid', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.+-]+\\.(edu|edu.pk)$')]),
        ),
    ]
