# Generated by Django 3.2.5 on 2021-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20210719_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(choices=[('Super_User', 'Super_User'), ('Account_Admin', 'Account_Admin'), ('Head_of_Subject', 'Head_of_Subject'), ('Subject_Teacher', 'Subject_Teacher'), ('Head_Teacher', 'Head_Teacher'), ('Print_Manager', 'Print_Manager'), ('TBD', 'TBD')], default='TBD', max_length=100),
        ),
    ]
