# Generated by Django 3.2.5 on 2021-07-27 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_domain', message='Domain not valid', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.+-]+\\.(edu|edu.pk|)$')]),
        ),
    ]
