# Generated by Django 3.2.5 on 2021-07-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QLA', '0011_alter_school_name'),
        ('Users', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.school'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
