# Generated by Django 3.2.5 on 2021-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=100)),
                ('Facebook', models.URLField(max_length=100)),
                ('Instagram', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contactus',
            },
        ),
    ]
