# Generated by Django 3.2.5 on 2021-07-28 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QLA', '0009_alter_school_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStart', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('Transaction_ID', models.CharField(max_length=100)),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.school')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QLA.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscription',
            },
        ),
    ]
