# Generated by Django 3.2.5 on 2021-07-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0002_subscription_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='PaymentMethod',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe')], default='Paypal', max_length=100),
            preserve_default=False,
        ),
    ]
