# Generated by Django 3.2.5 on 2021-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0003_subscription_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order_payer_birth_date',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_payer_email_address',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_payer_name_given_name',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_payer_name_surname',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_payer_payer_id',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_payer_phone',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_purchase_units_amount_currency_code',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_purchase_units_amount_value',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_purchase_units_payee_email_address',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_purchase_units_payee_merchant_id',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_status',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_time',
            field=models.CharField(blank=True, help_text='For Paypal only', max_length=255, null=True),
        ),
    ]
