# Generated by Django 3.2.5 on 2021-07-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0001_initial'),
        ('Subscription', '0004_auto_20210729_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bundle.bundle'),
        ),
    ]
