# Generated by Django 3.2.5 on 2021-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0005_subscription_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Email',
            field=models.CharField(default='abdullahrafi@test.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='Name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='Phone',
            field=models.CharField(default='test number', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='ciyt',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='country',
            field=models.CharField(default='tst', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='state',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
