# Generated by Django 3.2.5 on 2021-07-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0006_auto_20210730_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='ciyt',
            new_name='city',
        ),
    ]
