# Generated by Django 3.2.5 on 2021-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0007_rename_ciyt_subscription_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Phone',
            new_name='lastName',
        ),
        migrations.AddField(
            model_name='subscription',
            name='phone',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
    ]
