# Generated by Django 3.2.5 on 2021-07-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0008_auto_20210730_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='state',
            new_name='State',
        ),
    ]
