# Generated by Django 3.2.5 on 2021-08-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0009_auto_20210730_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Price',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
